name: quark
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.16
  - numpy=1.24.1
  - pandas=1.5.3
  - seaborn=0.12.2
  - pip=23.0
  - pip:
      - networkx==2.8.8
      - pennylane==0.28.0
      - pennylane-lightning==0.28.2
      - amazon-braket-pennylane-plugin==1.5.2
      - python-sat==0.1.7.dev26
      - dwave-samplers==1.0.0
      - nnf==0.4.1
      - pyqubo==1.4.0
      - dwave_networkx==0.8.13
      - qiskit==0.40.0
      - qiskit-optimization==0.5.0
      - scikit-learn==1.2.1
      - pyyaml==6.0
      - qubovert==1.2.5
      - inquirer==3.1.2
      - more-itertools==9.0.0
